[project]
name = "batch-builder"
authors = ["Stacks Community"]
description = "Decentralized batch processing and task coordination toolkit"
telemetry = false
requirements = []

[contracts.batch-coordinator]
path = "contracts/batch-coordinator.clar"
depends_on = []

[contracts.task-registry]
path = "contracts/task-registry.clar"
depends_on = []

[contracts.reward-allocation]
path = "contracts/reward-allocation.clar"
depends_on = []

[contracts.batch-treasury]
path = "contracts/batch-treasury.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
